// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v4.24.4
// source: search/v1/search.proto

package searchv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	SearchService_SearchProducts_FullMethodName  = "/search.v1.SearchService/SearchProducts"
	SearchService_SuggestProducts_FullMethodName = "/search.v1.SearchService/SuggestProducts"
	SearchService_IndexProduct_FullMethodName    = "/search.v1.SearchService/IndexProduct"
	SearchService_ReindexCatalog_FullMethodName  = "/search.v1.SearchService/ReindexCatalog"
)

// SearchServiceClient is the client API for SearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SearchService provides full-text search, suggestions, and product indexing.
type SearchServiceClient interface {
	// SearchProducts performs full-text search with filters and sorting.
	SearchProducts(ctx context.Context, in *SearchProductsRequest, opts ...grpc.CallOption) (*SearchProductsResponse, error)
	// SuggestProducts returns autocomplete suggestions.
	SuggestProducts(ctx context.Context, in *SuggestProductsRequest, opts ...grpc.CallOption) (*SuggestProductsResponse, error)
	// IndexProduct indexes a single product into Elasticsearch.
	IndexProduct(ctx context.Context, in *IndexProductRequest, opts ...grpc.CallOption) (*IndexProductResponse, error)
	// ReindexCatalog reindexes all products from Catalog Service.
	ReindexCatalog(ctx context.Context, in *ReindexCatalogRequest, opts ...grpc.CallOption) (*ReindexCatalogResponse, error)
}

type searchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchServiceClient(cc grpc.ClientConnInterface) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) SearchProducts(ctx context.Context, in *SearchProductsRequest, opts ...grpc.CallOption) (*SearchProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchProductsResponse)
	err := c.cc.Invoke(ctx, SearchService_SearchProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) SuggestProducts(ctx context.Context, in *SuggestProductsRequest, opts ...grpc.CallOption) (*SuggestProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuggestProductsResponse)
	err := c.cc.Invoke(ctx, SearchService_SuggestProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) IndexProduct(ctx context.Context, in *IndexProductRequest, opts ...grpc.CallOption) (*IndexProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexProductResponse)
	err := c.cc.Invoke(ctx, SearchService_IndexProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) ReindexCatalog(ctx context.Context, in *ReindexCatalogRequest, opts ...grpc.CallOption) (*ReindexCatalogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReindexCatalogResponse)
	err := c.cc.Invoke(ctx, SearchService_ReindexCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServiceServer is the server API for SearchService service.
// All implementations must embed UnimplementedSearchServiceServer
// for forward compatibility
//
// SearchService provides full-text search, suggestions, and product indexing.
type SearchServiceServer interface {
	// SearchProducts performs full-text search with filters and sorting.
	SearchProducts(context.Context, *SearchProductsRequest) (*SearchProductsResponse, error)
	// SuggestProducts returns autocomplete suggestions.
	SuggestProducts(context.Context, *SuggestProductsRequest) (*SuggestProductsResponse, error)
	// IndexProduct indexes a single product into Elasticsearch.
	IndexProduct(context.Context, *IndexProductRequest) (*IndexProductResponse, error)
	// ReindexCatalog reindexes all products from Catalog Service.
	ReindexCatalog(context.Context, *ReindexCatalogRequest) (*ReindexCatalogResponse, error)
	mustEmbedUnimplementedSearchServiceServer()
}

// UnimplementedSearchServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSearchServiceServer struct {
}

func (UnimplementedSearchServiceServer) SearchProducts(context.Context, *SearchProductsRequest) (*SearchProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchProducts not implemented")
}
func (UnimplementedSearchServiceServer) SuggestProducts(context.Context, *SuggestProductsRequest) (*SuggestProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SuggestProducts not implemented")
}
func (UnimplementedSearchServiceServer) IndexProduct(context.Context, *IndexProductRequest) (*IndexProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IndexProduct not implemented")
}
func (UnimplementedSearchServiceServer) ReindexCatalog(context.Context, *ReindexCatalogRequest) (*ReindexCatalogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReindexCatalog not implemented")
}
func (UnimplementedSearchServiceServer) mustEmbedUnimplementedSearchServiceServer() {}

// UnsafeSearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchServiceServer will
// result in compilation errors.
type UnsafeSearchServiceServer interface {
	mustEmbedUnimplementedSearchServiceServer()
}

func RegisterSearchServiceServer(s grpc.ServiceRegistrar, srv SearchServiceServer) {
	s.RegisterService(&SearchService_ServiceDesc, srv)
}

func _SearchService_SearchProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).SearchProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_SearchProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).SearchProducts(ctx, req.(*SearchProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_SuggestProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuggestProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).SuggestProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_SuggestProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).SuggestProducts(ctx, req.(*SuggestProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_IndexProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).IndexProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_IndexProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).IndexProduct(ctx, req.(*IndexProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_ReindexCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReindexCatalogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).ReindexCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_ReindexCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).ReindexCatalog(ctx, req.(*ReindexCatalogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchService_ServiceDesc is the grpc.ServiceDesc for SearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "search.v1.SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchProducts",
			Handler:    _SearchService_SearchProducts_Handler,
		},
		{
			MethodName: "SuggestProducts",
			Handler:    _SearchService_SuggestProducts_Handler,
		},
		{
			MethodName: "IndexProduct",
			Handler:    _SearchService_IndexProduct_Handler,
		},
		{
			MethodName: "ReindexCatalog",
			Handler:    _SearchService_ReindexCatalog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "search/v1/search.proto",
}
