"""gRPC service implementation for the Admin Service.

This file is auto-generated from the protobuf definition and implements
the ``AdminService`` RPCs.  It delegates to ``AdminService`` business
logic for every call.
"""

from typing import Any

import grpc
from google.protobuf.empty_pb2 import Empty
from google.protobuf.timestamp_pb2 import Timestamp

# ---------------------------------------------------------------------------
# NOTE: The following stubs are placeholders.  In production the
# ``admin_pb2`` and ``admin_pb2_grpc`` modules are generated by
# ``grpc_tools.protoc`` from the ``admin.proto`` descriptor.
# ---------------------------------------------------------------------------
# from src.proto.admin_pb2 import (
#     LoginAdminRequest,
#     LoginAdminResponse,
#     GetDashboardStatsRequest,
#     DashboardStats,
#     ManageProductRequest,
#     ManageProductResponse,
#     ManageSellerRequest,
#     ManageSellerResponse,
#     GetAuditLogsRequest,
#     AuditLogEntry,
#     AssignRoleRequest,
#     AssignRoleResponse,
# )
# from src.proto.admin_pb2_grpc import AdminServiceServicer, AdminServiceServicer

from src.services.admin_service import AdminService


class AdminServiceServicer:
    """gRPC handler that delegates to ``AdminService``."""

    def __init__(self, admin_service: AdminService) -> None:
        self._admin_service = admin_service

    # -- LoginAdmin --------------------------------------------------------

    async def LoginAdmin(
        self, request: Any, context: grpc.aio.ServicerContext
    ) -> Any:
        token = request.token
        ip_address = (
            context.peer().split(":")[-1] if context.peer() else None
        )
        result = await self._admin_service.login_admin(token, ip_address=ip_address)
        # return LoginAdminResponse(**result)  # type: ignore[arg-type]
        return result  # type: ignore[return-value]

    # -- GetDashboardStats -------------------------------------------------

    async def GetDashboardStats(
        self, request: Any, context: grpc.aio.ServicerContext
    ) -> Any:
        token = request.token
        stats = await self._admin_service.get_dashboard_stats(token)
        # return DashboardStats(**stats)  # type: ignore[arg-type]
        return stats  # type: ignore[return-value]

    # -- ManageProduct -----------------------------------------------------

    async def ManageProduct(
        self, request: Any, context: grpc.aio.ServicerContext
    ) -> Any:
        token = request.token
        ip_address = (
            context.peer().split(":")[-1] if context.peer() else None
        )
        result = await self._admin_service.manage_product(
            token, request.product_id, request.status, ip_address=ip_address
        )
        # return ManageProductResponse(**result)  # type: ignore[arg-type]
        return result  # type: ignore[return-value]

    # -- ManageSeller ------------------------------------------------------

    async def ManageSeller(
        self, request: Any, context: grpc.aio.ServicerContext
    ) -> Any:
        token = request.token
        ip_address = (
            context.peer().split(":")[-1] if context.peer() else None
        )
        result = await self._admin_service.manage_seller(
            token, request.seller_id, request.status, ip_address=ip_address
        )
        # return ManageSellerResponse(**result)  # type: ignore[arg-type]
        return result  # type: ignore[return-value]

    # -- GetAuditLogs ------------------------------------------------------

    async def GetAuditLogs(
        self, request: Any, context: grpc.aio.ServicerContext
    ) -> Any:
        token = request.token
        logs = await self._admin_service.get_audit_logs(
            token,
            entity_type=request.entity_type or None,
            entity_id=request.entity_id or None,
            limit=request.limit,
            offset=request.offset,
        )
        # return GetAuditLogsResponse(entries=logs)  # type: ignore[arg-type]
        return logs  # type: ignore[return-value]

    # -- AssignRole --------------------------------------------------------

    async def AssignRole(
        self, request: Any, context: grpc.aio.ServicerContext
    ) -> Any:
        token = request.token
        ip_address = (
            context.peer().split(":")[-1] if context.peer() else None
        )
        result = await self._admin_service.assign_role(
            token, request.admin_id, request.role, ip_address=ip_address
        )
        # return AssignRoleResponse(**result)  # type: ignore[arg-type]
        return result  # type: ignore[return-value]
